services:
  hikup-server:
    image: hikari03/hikup:stable
    container_name: hikup-server
    ports:
      - "6997:6997"
      - "6998:6998"
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - ./settings:/app/settings
      - ./storage:/app/storage